export const PROJECTS = [
    {
        id: 1,
        title: "動画編集自動化 AI",
        category: "claude-code",
        emoji: "🎬",
        image: "images/projects/p1.svg",
        summary: "無音・フィラーを自動検出してPremiere Pro用XMLを出力",
        description: "Claude Codeのスキルとして動画のトーク部分を解析。Whisperで文字起こし、silero-VADで無音検出、ffmpegで音量分析を行い、カット編集用のXMLファイルを自動生成する。",
        tags: ["Whisper", "ffmpeg", "silero-VAD"],
        links: { github: "", x: "" },
    },
    {
        id: 2,
        title: "テロップ自動生成ツール",
        category: "claude-code",
        emoji: "💬",
        image: "images/projects/p2.svg",
        summary: "編集済み動画からWhisper+Claudeでテロップ用SRTを生成",
        description: "編集済みシーケンスからWhisperで文字起こし後、Claude APIで整文・句読点付与を行い、フレーム同期したSRTファイルを出力する。",
        tags: ["Whisper", "SRT", "Claude API"],
        links: { github: "", x: "" },
    },
    {
        id: 3,
        title: "SEOブログ自動生成",
        category: "automation",
        emoji: "✍️",
        image: "images/projects/p3.svg",
        summary: "キーワードから1万字のSEOブログをAIが自動執筆",
        description: "指定キーワードとターゲット文字数をもとに、Claude APIがリサーチ→構成→執筆を自動実行。char-counterスキルで文字数を検証しながら最適化する。",
        tags: ["Claude API", "SEO", "Markdown"],
        links: { github: "", x: "" },
    },
    {
        id: 4,
        title: "RAGチャットボット",
        category: "claude-api",
        emoji: "🤖",
        image: "images/projects/p4.svg",
        summary: "PDF/ドキュメントに基づいて回答するClaudeアプリ",
        description: "社内ドキュメントやPDFをベクトルDBに格納し、Claude APIのRAGパターンで質問応答を実現。Anthropic SDKのprompt cachingで高速・低コストを実現。",
        tags: ["Anthropic SDK", "Vector DB", "Python"],
        links: { github: "", x: "" },
    },
    {
        id: 5,
        title: "Claude Code カスタムスキル集",
        category: "claude-code",
        emoji: "⚡",
        image: "images/projects/p5.svg",
        summary: "繰り返し作業を自動化するClaude Codeスキル集",
        description: "analyzer/builder/reviewer パイプライン、summarize、file-summaryなど業務自動化スキルを多数開発。スキルは.mdファイルとして管理しClaude Codeに読み込ませる。",
        tags: ["Claude Code", "Markdown", "YAML"],
        links: { github: "", x: "" },
    },
    {
        id: 6,
        title: "ポートフォリオサイト自動生成",
        category: "automation",
        emoji: "🌐",
        image: "images/projects/p6.svg",
        summary: "AIとの対話でポートフォリオサイトを自動構築",
        description: "brainstorming → writing-plans → executing-plans のスキルパイプラインを活用し、要件定義から実装まで全工程をClaude Codeで自動化したサイト（このサイト自体）。",
        tags: ["HTML/CSS/JS", "Claude Code", "自動化"],
        links: { github: "", x: "" },
    },
    {
        id: 7,
        title: "Xポスト自動生成",
        category: "automation",
        emoji: "𝕏",
        image: "images/projects/p7.svg",
        summary: "ブログ記事からバズりやすいXポストを自動生成",
        description: "記事URLを入力するとClaude APIが記事を要約し、エンゲージメントを最大化するXポスト文案を複数パターン生成する。",
        tags: ["Claude API", "X API", "Python"],
        links: { github: "", x: "" },
    },
    {
        id: 8,
        title: "Claude API バッチ処理ツール",
        category: "claude-api",
        emoji: "📊",
        image: "images/projects/p8.svg",
        summary: "大量データをClaude APIのバッチ処理で低コスト分析",
        description: "Anthropic Message Batch APIを活用し、CSVの大量テキストを50%コスト削減で分類・要約・感情分析する。進捗管理とリトライ機能付き。",
        tags: ["Batch API", "Anthropic SDK", "CSV"],
        links: { github: "", x: "" },
    },
    {
        id: 9,
        title: "Webスクレイパー＋AI要約",
        category: "web-app",
        emoji: "🔍",
        image: "images/projects/p9.svg",
        summary: "Webページを取得してAIが自動要約・構造化",
        description: "指定URLのWebページをスクレイプし、Claude APIで要約・カテゴリ分類・キーワード抽出を行う。結果をJSON/Markdownで出力。",
        tags: ["Python", "BeautifulSoup", "Claude API"],
        links: { github: "", x: "" },
    },
    {
        id: 10,
        title: "Gmail × Claude 自動返信",
        category: "automation",
        emoji: "📧",
        image: "images/projects/p10.svg",
        summary: "受信メールをClaudeが分類・返信案を自動作成",
        description: "Gmail APIで受信メールを取得し、Claude APIで内容を分類・返信文案を生成。Google Apps ScriptからClaude APIを呼び出し、承認後に送信する。",
        tags: ["Gmail API", "Claude API", "Google Apps Script"],
        links: { github: "", x: "" },
    },
    {
        id: 11,
        title: "音声メモ → タスク変換",
        category: "web-app",
        emoji: "🎙️",
        image: "images/projects/p11.svg",
        summary: "音声メモをWhisper文字起こし→Claudeでタスク整理",
        description: "録音した音声メモをWhisperで文字起こしし、Claude APIが内容を解析してタスク・期限・優先度に構造化、Notion DBへ自動登録する。",
        tags: ["Whisper", "Claude API", "Notion API"],
        links: { github: "", x: "" },
    },
    {
        id: 12,
        title: "コードレビュー自動化",
        category: "claude-api",
        emoji: "🔎",
        image: "images/projects/p12.svg",
        summary: "PRのdiffをClaudeが自動レビュー・コメント投稿",
        description: "GitHub WebhookでPR openイベントを受け取り、diffをClaude APIに送信してコードレビューコメントを自動生成・投稿する。セキュリティ・品質・パフォーマンスの観点で分析。",
        tags: ["GitHub API", "Claude API", "Webhook"],
        links: { github: "", x: "" },
    },
];
